language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "10"

sudo: false
dist: trusty

addons:
  chrome: stable
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - xvfb
      - g++-4.8

cache:
  yarn: true

env:
  global:
    - CXX=g++-4.8
    # See https://git.io/vdao3 for details.
    - JOBS=1

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/

jobs:
  include:
    - stage: test
      script: npm run test
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release


before_install:
  - yarn config set no-progress

install:
  - yarn --frozen-lockfile
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
